node:
  listen: :3000
  #  server: 127.0.0.1:4000
  registry: tiptopsoft.cn
  #  offset: 1
  #  relay:
  #    enable: true
  #  encrypt:
  #    enable: true
  #  auth:
  #    enable: true
  log:
    debug: true

#-------------------分害线
registry:
  listen: :4000
  httpListen: :4009
  redis:
    enable: true
    url: 211.158.125.186
    port: 6679
    username: winston
    password: 123456