client:
  listen: :3000
  server: 127.0.0.1:4000
#  server: 211.159.225.186:4000
  offset: 1
  relay:
    enable: true
  encrypt:
    enable: true
  auth:
    enable: true

#-------------------分害线
server:
  listen: :4000
  httpListen: :4009
  redis:
    enable: true
    url: 211.158.125.186
    port: 6679
    username: winston
    password: 123456